---
# tasks file for roles/create_network

# roles/create_network/tasks/main.yml

- name: Create Docker network
  docker_network:
    name: my_network
    driver: bridge
  vars:
    ansible_python_interpreter: /usr/bin/python3
