- name: Run Application
  docker_container:
    name: simple-api-student
    image: tcaraux/simple-api-student:latest
    env_file: /home/centos/application.yml
    networks:
      - name: my_network
    state: started
  vars:
    ansible_python_interpreter: /usr/bin/python3
    