# Utiliser l'image de httpd
FROM httpd:2.4

# Copier la page index.html dans le répertoire approprié
COPY index.html /usr/local/apache2/htdocs/

# Copier le fichier de configuration httpd.conf
COPY httpd.conf /usr/local/apache2/conf/httpd.conf
