name: CI devops 2024
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: 
      - main 
      - develop
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
     #checkout your github code using actions/checkout@v2.5.0
      - uses: actions/checkout@v2.5.0

     #do the same with another action (actions/setup-java@v3) that enable to setup jdk 17
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: 21

      # List files to verify the structure
      - name: List files in repository
        run: ls -R

     #finally build your app with the latest command
      - name: Build and test with Maven
        run: mvn clean verify --file simpleapi/pom.xml
